apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-echo-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-echo-server
  template:
    metadata:
      labels:
        app: node-echo-server
    spec:
      containers:
        - name: node-echo-server
          imagePullPolicy: Always
          env:
            - name: CURRENT_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          image: needkk/node-echo:v2.0.1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regsecret
---
apiVersion: v1
kind: Service
metadata:
  name: node-echo-svc
spec:
  type: NodePort
  ports:
    - protocol: TCP
      nodePort: 30080
      port: 80
      targetPort: 80
  selector:
    app: node-echo-server
